### PR TITLE
Issue #3 Enhancements

### PR DESCRIPTION
**Pull request by thbonk**
- Added targets for macOS
- Shared MastodonClient for iOS & macOS to provide Carthage compatibility

### CODE REVIEW

**Comment by DK1DA** [comment]
Do we have to import Foundation everywhere? I think Moya /  Gloss ar already importing them.

**Comment by DK1DA** [comment]
Happy to merge this, but In general I'd like to get away from the CocoaPods project setup (e.g the Example folder) I don't want to risk CocoaPods overriding anything on the next pod install (which it shouldn't do but who knows)

**Comment by DK1DA** [comment]
I'd refactor the project setup once we've dealt with all pending PRs.

**Comment by thbonk** [comment]
I think so. I got compile errors for the macOS targets; the Swift compiler wasn't able to find URL and Data.

-- 
Thomas Bonk
Ortsstraße 33 | D-66459 Kirkel-Altstadt | Germany | http://www.meandmymac.de/ 
mobile: +49-151-11658410 | mail: thomas@meandmymac.de 
twitter: http://twitter.com/thbonk | adn: https://alpha.app.net/thbonk

**Comment by DK1DA** [comment]
Ah sure, sorry my bad I only tested on iOS. Yeah the. letzend meege it

**Pull request merged**
